

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  ai:
    openai:
      api-key: xxxx
      chat:
        options:
          model: qwen/qwen2.5-3B-Instruct
        api-key: xxxx
        base-url: http://100.0.14.196:8088
      embedding:
        api-key: xxxx
        base-url: http://100.0.14.196:8088
        options:
          model: all-minilm:33m


#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen2.5:0.5b
#      embedding:
#        options:
#          model: all-minilm:33m
#          model: bge-m3
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: db-schema
        initialize-schema: true
    mcp:
      server:
        name: my-weather-server
        version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdpx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    cache: false

initVectorsData: false
systemPrompt: |
  You are a professional SQL development assistant and need to write accurate and efficient SQL queries based on the provided database table structure and specific questions. Please follow the following steps for analysis and generation.：
  1. Table structure analysis
     Read the following table structure carefully and pay attention to the field comments and associations：
  {}
  2. 查询需求解析
  3. Writing Requirements
     Please construct the SQL in the following order:
     (1) Identify the main table and associated tables involved.
     (2) Determine the appropriate JOIN type and connection conditions.
     (3) Parse the time range, status filtering, and other constraints in the WHERE condition.
     (4) Select the correct aggregation function and grouping conditions.
     (5) Design clear column aliases and result sorting.
     (6) invoke getSqlResult tool to obtain the results.

  4. Please pay special attention to the following points:
     (1) Prefer using EXISTS over IN subqueries.
     (2) Add table name prefixes to associated fields to avoid ambiguity.
     (3) Format the SQL to improve readability.
     (4) 使用中文输出解析，不要使用英文输出

  Please finally generate the executable complete SQL statement

sa-token:
  # token 名称 (同时也是 cookie 名称)
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # jwt 秘钥
  jwt-secret-key: JfdDSgfCmPsDfmsAaQwnXk

logging:
  level:
    root: warn
    org.springframework.web.client: debug
    cn.sd.ai: debug
    org.springframework.retry.support.RetryTemplate: debug
    org.springframework.web.servlet.resource: info  # 添加日志级别以排查静态资源问题